CREATE TABLE IF NOT EXISTS "customer_master" (
    "id" SERIAL NOT NULL,
    "customerType" TEXT NOT NULL,
    "cCode" TEXT NOT NULL,
    "customerName" TEXT NOT NULL,
    "address" TEXT,
    "address2" TEXT,
    "address3" TEXT,
    "address4" TEXT,
    "city" TEXT,
    "country" TEXT DEFAULT 'India',
    "state" TEXT,
    "stateCode" TEXT,
    "pinCode" TEXT,
    "contactPerson" TEXT,
    "mobile" TEXT,
    "phone" TEXT,
    "email" TEXT,
    "website" TEXT,
    "aadharNo" TEXT,
    "gstNo" TEXT,
    "panNo" TEXT,
    "bankName" TEXT,
    "branchName" TEXT,
    "accountName" TEXT,
    "accountNumber" TEXT,
    "ifscCode" TEXT,
    "micrCode" TEXT,
    "remarks" TEXT,
    "createdBy" TEXT,
    "updatedBy" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "customer_master_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "customer_master_cCode_key" ON "customer_master"("cCode");
