export const ErrorCodes = {
  // Auth & Permissions
  UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  FORBIDDEN: "AUTH_FORBIDDEN",
  TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  ACCOUNT_DEACTIVATED: "AUTH_ACCOUNT_DEACTIVATED",

  // Request & Validation
  BAD_REQUEST: "REQ_BAD_REQUEST",
  VALIDATION_ERROR: "REQ_VALIDATION_ERROR",
  INVALID_PAYLOAD: "REQ_INVALID_PAYLOAD",
  MISSING_REQUIRED_FIELD: "REQ_MISSING_REQUIRED_FIELD",
  RESOURCE_NOT_FOUND: "REQ_RESOURCE_NOT_FOUND",
  ROUTE_NOT_FOUND: "REQ_ROUTE_NOT_FOUND",

  // Conflict & Business Logic
  CONFLICT: "BIZ_CONFLICT",
  DUPLICATE_RECORD: "BIZ_DUPLICATE_RECORD",
  FOREIGN_KEY_VIOLATION: "BIZ_FOREIGN_KEY_VIOLATION",

  // File Upload
  FILE_UPLOAD_ERROR: "FILE_UPLOAD_ERROR",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  INVALID_FILE_TYPE: "FILE_INVALID_TYPE",

  // Database & System
  DATABASE_ERROR: "SYS_DATABASE_ERROR",
  DATABASE_CONNECTION_FAILURE: "SYS_DATABASE_CONN_FAILURE",
  INTERNAL_SERVER_ERROR: "SYS_INTERNAL_SERVER_ERROR",
  UNEXPECTED_ERROR: "SYS_UNEXPECTED_ERROR",
};
